#!/bin/bash

# term colorsheme
#xrdb merge ~/.Xresources &

# Autostart apps
numlockx &
pgrep -x sxhkd > /dev/null || sxhkd > /tmp/sxhkd.log 2>&1 & disown

picom > /tmp/picom.log 2>&1 &

# polybar 
~/.config/polybar/launch.sh &

# wallpaper
feh --bg-fill ~/.wallpaper &

# Fix X cursor
xsetroot -cursor_name left_ptr &

#
# workspaces 
#
bspc monitor -d 1 2 3 4
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focus_follows_pointer true

DEFAULT_W_GAP=6
DEFAULT_BAR_HEIGHT=72

#
# borders
#
bspc config focused_border_color "#637c95"
bspc config normal_border_color "#4F5766"
bspc config border_width 1
bspc config borderless_monocle false

#
# gaps 
#
bspc config gapless_monocle true
bspc config window_gap $DEFAULT_W_GAP
bspc config top_padding $DEFAULT_BAR_HEIGHT
bspc config bottom_padding 10
bspc config left_padding 14
bspc config right_padding 14
bspc config split_ratio 0.50

#
# Window rules
#
bspc rule -a Steam desktop='^4' state=floating
bspc rule -a Pavucontrol state=floating rectangle=720x480
bspc rule -a qemu-system-i386 desktop='^4' state=floating rectangle=1280x720
bspc rule -a URxvt desktop='^3' state=floating rectangle=720x480
bspc rule -a qemu-system-x86_64 desktop='^4' state=floating
bspc rule -a Qemu-system-x86_64 desktop='^4' state=floating #rectangle=1280x720


# bscpc rule -a firefox border=off
# bscpc rule -a Alacritty border=on
# bspc rule -a mpv state=floating rectangle=WidthxHeight+Xoffset+Yoffset

bspc config single_monocle true
bspc config left_monocle_padding 350
bspc config right_monocle_padding 350
bspc config top_monocle_padding 100
bspc config bottom_monocle_padding 100
