#!/bin/bash

# term colorsheme
#xrdb merge ~/.Xresources &

# Autostart apps
pgrep -x sxhkd > /dev/null || sxhkd > /tmp/sxhkd.log 2>&1 & disown

# picom &

# polybar 
~/.config/polybar/launch.sh &

# wallpaper
feh --bg-fill ~/.wallpaper &

# Fix X cursor
xsetroot -cursor_name left_ptr &

#
# workspaces 
#
bspc monitor -d 1 2 3 4

bspc config focus_follows_pointer true

DEFAULT_W_GAP=20
DEFAULT_BAR_HEIGHT=40

#
# borders
#
bspc config focused_border_color "#637c95"
bspc config normal_border_color "#4F5766"
bspc config border_width 2
bspc config borderless_monocle false

#
# gaps 
#
bspc config gapless_monocle false
bspc config window_gap $DEFAULT_W_GAP
bspc config top_padding $DEFAULT_BAR_HEIGHT
bspc config split_ratio 0.50

#
# Window rules
#
# bspc rule -a Firefox state=fullscreen
# bspc rule -a mpv state=floating rectangle=WidthxHeight+Xoffset+Yoffset

# bspc config single_monocle true
# bspc config left_monocle_padding $DEFAULT_W_GAP
# bspc config right_monocle_padding $DEFAULT_W_GAP
# bspc config top_monocle_padding $DEFAULT_W_GAP
# bspc config bottom_monocle_padding $DEFAULT_W_GAP

#
# Dynamic window gaps based on number of active windows
#
 
TERMINAL_APP="Alacritty"
FILE_APP="Thunar"

getWindowClassName () {
  echo $(bspc query -T -n $1 | grep -oP '(?<="className":")[^"]*')
}

bspc subscribe node_add node_remove | while read line; do
  W_LIST=$(bspc query -N -n .local.tiled)
  W_COUNT=$(echo ${W_LIST} | wc -w)

  W_GAP=$DEFAULT_W_GAP
  D_PAD_LEFT=0
  D_PAD_RIGHT=0

  if [ $W_COUNT = "1" ]; then
    W_CLASSNAME=$(getWindowClassName ${W_LIST})
    if [ $W_CLASSNAME = $TERMINAL_APP ] || [ $W_CLASSNAME = $FILE_APP ]; then
      W_GAP=400
      D_PAD_LEFT=450
      D_PAD_RIGHT=450
    else
      W_GAP=150
      D_PAD_LEFT=225
      D_PAD_RIGHT=225
    fi
  elif [ $W_COUNT = "2" ]; then
    W_GAP=$DEFAULT_W_GAP
  fi
  # [[ $W_GAP -lt $DEFAULT_W_GAP ]] && W_GAP=$DEFAULT_W_GAP
  bspc config --desktop focused window_gap $W_GAP
  bspc config left_padding $D_PAD_LEFT
  bspc config right_padding $D_PAD_RIGHT
done